name: Website Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, labeled, unlabeled, synchronize, ready_for_review]

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
  check-style:
    name: Check Styles
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Check Style
        run: yarn check-style
  check-types:
    name: Check Types
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Check Types
        run: yarn check-types
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Test
        run: yarn test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
  build-website:
    name: Website Build
    runs-on: ubuntu-latest
    needs: [check-style, check-types]
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Build
        run: yarn build
      - name: Cache next-app-build # stored for later use
        uses: actions/cache@v2
        with:
          path: '.next'
          key: ${{ runner.os }}-${{ github.run_number }}-next-${{ hashFiles('yarn.lock') }}
  build-storybook:
      name: Storybook Build
      runs-on: ubuntu-latest
      needs: [check-style, check-types]
      timeout-minutes: 5
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
        - name: Cache node_modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
        - name: Build
          run: yarn build-storybook
        - name: Cache storybook build
          uses: actions/cache@v2
          with:
            path: 'storybook-static'
            key: ${{ runner.os }}-${{ github.run_number }}-storybook-${{ hashFiles('yarn.lock') }}
  chromatic-deployment:
    name: Chromatic Deployment
    if: github.ref == 'refs/heads/master' || ( github.event.pull_request && ! github.event.pull_request.draft )
    runs-on: ubuntu-latest
    needs: build-storybook
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Cache storybook build
        uses: actions/cache@v2
        with:
          path: 'storybook-static'
          key: ${{ runner.os }}-${{ github.run_number }}-storybook-${{ hashFiles('yarn.lock') }}
      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          storybookBuildDir: 'storybook-static'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
